### ISSUE TITLE
3.1.0 release introduced CommonJS regressions

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#100]
The 3.1.0 release tag includes cf91f81e125 which removed `WebCola/cola.v[123].min.js` in favour of a single `WebCola/cola.min.js`.  Whilst this was a very good change to have in the `master` branch (in fact [it's what I previously suggested](https://github.com/tgdwyer/WebCola/issues/58#issuecomment-69481024)), [it broke `git-deps`](https://github.com/aspiers/git-deps#49) because the change neglected to update the `"main"` entry point in `package.json` accordingly.  The fix for `package.json` came later in 1cf5dcc5f84 (although it was hidden behind an unrelated commit message "don't use yuidoc"), but that commit is after the 3.1.0 release tag, therefore the 3.1.0 release is unusable by `git-deps` and any other CommonJS-based consumer.

Another problem is that in 2b26a2a143, @qinfchen bumped the version in `bower.json` from 3.0.1 to 3.1.0, but neglected to make the same change in `package.json`.

So I think it would be worth bumping both `bower.json` and `package.json` to 3.1.1, and then making a new `v3.1.1` tag, otherwise the latest release is ~~broken for CommonJS-based consumers~~ *(EDIT)* further away from CommonJS support than previous versions.  (See #44 for issues relating to full CommonJS support.)

Without wishing to sound in any way ungrateful for this fantastic project (without which git-deps would not have been anywhere near as successful), it would be great if you could bear in mind that there is now at least one downstream project which is relying on WebCola having a predictable release strategy ;-)  So if you could maintain releases with stable APIs according to [SemVer](http://semver.org/), that would help avoid breaking downstream projects, the maintainer(s) of which would be super grateful ;-)

Thanks for listening!

**Comment by aspiers** [comment]
OK, so it seems my memory was a little hazy.  I had forgotten that CommonJS support still does not exist out of the box, as per #44.  However this regression does not make matters easier ;-)

**Comment by tgdwyer** [comment]
Is this resolved now?

**Comment by aspiers** [comment]
I would guess so but I'll have to test.

**Comment by tgdwyer** [comment]
see also [this commit](https://github.com/tgdwyer/WebCola/commit/541e66a28c23069807064d1189cd33fed5cd0f09)

**Comment by tgdwyer** [comment]
closing for now, see #129 which I will leave open until we get a proper npm release
