### ISSUE TITLE
prevent edge overlap ?

### ISSUE THREAD

**Issue by AjitPS** [tgdwyer/WebCola#106]
Hi, is there a way to prevent <b>edge overlap</b> (in addition to node overlap which is achieved via ```avoidOverlap: true```) while using the Cola layout ?

**Comment by AjitPS** [comment]
Any suggestions ?

**Comment by tgdwyer** [comment]
Sorry for the slow reply.

It depends what exactly you mean by edge overlap.  If you mean co-linear edges such as duplicate edges between the same pair of nodes, then the layout engine does not do anything with them.  You can fix them up yourself when you draw the edges.  For example, this cola based system takes great care when drawing such edges:

http://immersive.erc.monash.edu.au/stac/

If you mean edges overlapping nodes, then you can use cola's polyline routing to have edges routed carefully around node boxes, as described in this example:

http://marvl.infotech.monash.edu/webcola/examples/unix.html

However, the above doesn't do anything with the colinear edge case.  Again, you would need to offset the edges yourself (for the moment).  I am experimenting with a "grid" layout style with routing that carefully keeps all the edges nicely routed and separated, e.g.:
