### ISSUE TITLE
Is there a way to set sticky nodes?

### ISSUE THREAD

**Issue by kristw** [tgdwyer/WebCola#107]
There are several nodes in the network that I want to fix their positions. 
From reading the documentation, I guess I have to set two constraints for each of the sticky nodes to fix their x and y. Is there an easier way to achieve the same results?

**Comment by tgdwyer** [comment]
No, the best way to fix the position of a node is by setting its``` x,y``` yourself and then setting ```fixed=true```.

I get this question a lot, so I wrote up a quick wiki page with some info:
https://github.com/tgdwyer/WebCola/wiki/Fixed-Node-Positions

**Comment by kristw** [comment]
Thank you.
