### ISSUE TITLE
I have a few questions

### ISSUE THREAD

**Issue by kristw** [tgdwyer/WebCola#109]
Hi Cola team,

- Is there any documentation on how function start() work?
- Currently tick event is dispatched every iteration. Is there a way to improve the speed of the simulation and have less frequent tick events? I am trying to use cola for one layout optimization problem and compare with another algorithm. Now it's hard to compare the execution time. 
- Does cola fire any event when the simulation is stable? When can I tell that it has stop moving nodes, programmatically?

Thank you in advance.

-Krist

**Comment by tgdwyer** [comment]
1) Only [this](http://marvl.infotech.monash.edu/webcola/doc/classes/cola.layout.html#start), which I realize is a bit... brief:


2) you don't have to redraw every single tick - rather you could have a tick call-back that re-renders only every nth tick, for example.  You can do a completely off-line layout just by specifying numbers of iterations to apply in the ```start()``` method, as per the docs and examples such as [this](http://marvl.infotech.monash.edu/webcola/examples/unix.html).

3) the end event files on convergence.  Note that you can adjust the ```Layout.convergenceThreshold``` trade off layout quality with speed
