### ISSUE TITLE
Behavioral difference between minified and non-minified production js files

### ISSUE THREAD

**Issue by ronichoudhury** [tgdwyer/WebCola#111]
Hi!

Love Cola, thanks for working on it!

I have noticed a difference in how Cola handles "fixed" nodes between the [minified](http://marvl.infotech.monash.edu/webcola/cola.v3.min.js) and [unminified](http://marvl.infotech.monash.edu/webcola/cola.v3.js) hosted JS files.  I am not sure exactly what is causing it, but when I change to the unminified file in my project, suddenly nodes no longer stay fixed when I ask them to (in my application, I am setting the ``fixed`` property on all nodes to true while I make changes to the graph, then remove the property just after all changes to the graph have animated into place - this prevents visual confusion when nodes might otherwise suddenly pop to new positions, etc.).

For completeness' sake, the MD5 sums for the files I'm using are: 148b898ad9cbf34261cea26b1836b6ae (minified) and 28233e5218f6ed96b9f0aab9c3e88d71 (unminified).

This is not *exactly* a bug report because the correct behavior appears in the minified file, which means there is no problem for me; however, I thought you might like to know about the inconsistency.  In any case, it definitely caused me some confusion when I switched to the unminified file for debugging purposes, and couldn't understand why suddenly the nodes weren't behaving nicely anymore.

Thanks!

**Comment by tgdwyer** [comment]
Hi Roni,

Thanks for reporting this issue.  It sounds like a versioning issue (most
likely my fault).  Rather than using my marvl server I would recommend
getting the latest bits from
https://github.com/tgdwyer/WebCola/blob/master/WebCola/cola.js  (and
there's a minified version too).

For one thing, the ones with "v3" in the file name are quite old.

Cheers,

Tim

On 30 May 2015 at 08:34, Roni Choudhury <notifications@github.com> wrote:

> Hi!
>
> Love Cola, thanks for working on it!
>
> I have noticed a difference in how Cola handles "fixed" nodes between the
> minified <http://marvl.infotech.monash.edu/webcola/cola.v3.min.js> and
> unminified <http://marvl.infotech.monash.edu/webcola/cola.v3.js> hosted
> JS files. I am not sure exactly what is causing it, but when I change to
> the unminified file in my project, suddenly nodes no longer stay fixed when
> I ask them to (in my application, I am setting the fixed property on all
> nodes to true while I make changes to the graph, then remove the property
> just after all changes to the graph have animated into place - this
> prevents visual confusion when nodes might otherwise suddenly pop to new
> positions, etc.).
>
> For completeness' sake, the MD5 sums for the files I'm using are:
> 148b898ad9cbf34261cea26b1836b6ae (minified) and
> 28233e5218f6ed96b9f0aab9c3e88d71 (unminified).
>
> This is not *exactly* a bug report because the correct behavior appears
> in the minified file, which means there is no problem for me; however, I
> thought you might like to know about the inconsistency. In any case, it
> definitely caused me some confusion when I switched to the unminified file
> for debugging purposes, and couldn't understand why suddenly the nodes
> weren't behaving nicely anymore.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgdwyer/WebCola/issues/111>.
>



-- 
Dr Tim Dwyer BSc BCS(Hons) PhD
Senior Lecturer and Larkins Fellow
Caulfield School of Information Technology
Mobile: 0481 240 767
(from overseas: +61 481 240 767)

**Comment by ronichoudhury** [comment]
Thanks for such a quick response.

I didn't realize the repo hosts a more "cutting-edge" built library.  I may move my build process to keep a copy of that file in my sources to maintain stability, while knowing I can pull newer versions of that file to get new features/fixups/etc.

Thanks again!
