### ISSUE TITLE
cola - movies example - spikes showing sub-nodes

### ISSUE THREAD

**Issue by AjitPS** [tgdwyer/WebCola#115]
In the movies example (at http://marvl.infotech.monash.edu/webcola/examples/browsemovies.html), I noticed that hovering on each node shows small <b>spikes</b> corresponding to the number of sub-nodes that it shows once expanded.
Is this feature available in WebCola or was it implemented using <b>D3.js</b> ? I am using WebCola with <b><i>cytoscapeJS</i></b> and it would be great to have such a feature (visual aspect) that could be used via WebCola.

**Comment by tgdwyer** [comment]
See the [hintNeighbours function](
https://github.com/tgdwyer/WebCola/blob/master/WebCola/examples/browsemovies.html#L138)

I use D3 to actually draw the "spikes" which are just rotated rectangles with a gradient.   The logic is pretty simple and could be done just as easily in any graphics library.
