### ISSUE TITLE
Route Edge "Cannot read p of undefined"

### ISSUE THREAD

**Issue by emeeks** [tgdwyer/WebCola#116]
In attempting to utilize the routeEdging functionality on a similarly small graph (26 nodes, 50 edges) following the unix example (with bbox and padding margins) I get the following error:

Uncaught TypeError: Cannot read property 'p' of undefinedLayout.routeEdge @ cola.min.js:3925

Any clues on why this would happen?

**Comment by emeeks** [comment]
This seems to occur when nodes overlap despite the avoidOverlaps setting.

**Comment by tgdwyer** [comment]
Hi Elijah,

Yes, bad things will happen if you try to perform routing when there are
overlaps between the obstacles in the visibility graph.

My question then, is why are there overlaps between node boxes if the
avoidOverlaps option is turned on?

You will notice in this example:
http://marvl.infotech.monash.edu/webcola/examples/unix.html

that I only apply routing when layout is finished - and thus overlap free,
in the layout "end" event handler.  If you don't want to animate the layout
by listening for layout ticks, you can do an entire layout pass with a
single call to Layout.start(30,20,10).  the three numerical arguments are
numbers of iterations to apply of the different layout "stages".  The third
parameter is the number of iterations of non-overlap layout to apply.  This
must be non-zero to actually obtain an overlap free layout.

could this be your problem?

Please look closely at the unix example above and make sure that the margin
that you specify on the prepareEdgeRouting function is small enough that
the visibility graph is still overlap free.

Does all that make sense?

Cheers,
Tim

On 16 June 2015 at 23:56, Elijah Meeks <notifications@github.com> wrote:

> This seems to occur when nodes overlap despite the avoidOverlaps setting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgdwyer/WebCola/issues/116#issuecomment-112441080>.
>



-- 
Dr Tim Dwyer BSc BCS(Hons) PhD
Senior Lecturer and Larkins Fellow
Caulfield School of Information Technology
Mobile: 0481 240 767
(from overseas: +61 481 240 767)

**Comment by emeeks** [comment]
Yes, that's the example I was following, and I was applying routeEdges after the graph had finished laying out. But, sometimes, nodes were still overlapping and I'd get this error. It's definitely an edge case, but maybe it should draw a line through if it cannot drawing the edge within the constraints of the settings and the topology.

**Comment by tgdwyer** [comment]
did you have any luck with this?  Another thing that could cause overlaps to not be properly resolved is if you are also passing in a complex set of alignment or other equality constraints leading to infeasibility when non-overlap constraints are generated.  Please check that also.

**Comment by tgdwyer** [comment]
I'm going to close this for now, please reopen if you are still able to reproduce.
