### ISSUE TITLE
Example of dynamic axis constraint

### ISSUE THREAD

**Issue by emeeks** [tgdwyer/WebCola#120]
I have nodes that have a year of creation attribute and I'd like their x or y position to be dependent on a scaled, fixed value based on that attribute but I don't see any examples of how to pass a constraint like that.

So, nodes that are like this:

id: 0,
label: "News Article",
publication: 1985

And a traditional d3.scale.linear().domain([1980,2015]).range(displayWidth)

Using d3.layout.force I'd override node.px/x or .py/y at the tick function but doing the same with d3cola doesn't seem to affect node position. Is there a better/more elegant way to define and enact this constraint?

**Comment by tgdwyer** [comment]
I'm not sure I follow.  Do you mean you want the node's y (or possibly x position) to be proportional to (for example) the year of publication?  We can definitely do that, it's not going to be quite as easy as mapping with the d3.scale function though.

Rather, we would have to create dummy nodes for each year (which we would not draw), lock them in position at the required y position (you could use the scale function here if you like), and then create an alignment constraint for all the real nodes with that year and the dummy node for the year.

Let me know if you need more help with this.

Cheers,

Tim

**Comment by tgdwyer** [comment]
closing for now, please reopen if you think this is a necessary feature.
