### ISSUE TITLE
CommonJS regression caused by commit 7ad09c6

### ISSUE THREAD

**Issue by confiks** [tgdwyer/WebCola#123]
When including WebCola on commit 7ad09c6 (or later) using Webpack (which uses CommonJS), you get an error: `Module not found: Error: Cannot resolve 'file' or 'directory' ./src/rbtree in [path to webpack root]/node_modules/webcola/WebCola`

This seems to be caused by a line in .gitignore introduced in 7ad09c6 (`WebCola/*/*.js`), which ignores built files that are already in the repository. Apparently Webpack barfs over requiring a file which is present, but ignored by git.

**Comment by tgdwyer** [comment]
OK, I've removed that line.  Actually, it probably would have caused other problems anyway since we do have legitimate (not-generated) js files in the repository.  Hopefully this fixes the issue?

**Comment by confiks** [comment]
Yep, works like a charm. Thanks!
