### ISSUE TITLE
npm publish latest version

### ISSUE THREAD

**Issue by programmarchy** [tgdwyer/WebCola#129]
The last `npm publish` looks like it was version 0.1.1. Since then it looks like there have been many improvements! I would love to be able to use this package with browserify, too. Would someone please publish the latest version? Pinging @jkschneider because he published the last version.

**Comment by tgdwyer** [comment]
+1, I'm an absolute novice with npm but if someone who knows what they're doing (like @jkschneider) could have a go I'd appreciate it.

**Comment by anvaka** [comment]
@tgdwyer you will need to register your user on npm. Just run [`npm adduser`](https://docs.npmjs.com/cli/adduser) and it will guide you through the registration. After this is done, let us know your login name.

Once done, @jkschneider will need to add you as an [owner](https://docs.npmjs.com/cli/owner) of the package. For example if Tim registers as `tgdwyer` then the command will be `npm owner add tgdwyer webcola`.

This will let Tim run [`npm publish`](https://docs.npmjs.com/cli/publish) from the project root folder (where  `package.json` file is) and update to the newer version. Or, even better, use [`npm version`](https://docs.npmjs.com/cli/version) to manager versions. For example `npm version 3.1.2` will update package.json, create a git tag `3.1.2`. Then you can do `git push && git push --tags` to push it to github and follow up with `npm publish` to publish to npm registry.

PS: @programmarchy as a temporary workaround you can use 

`npm install tgdwyer/WebCola#db8826312b9a14ea96de5cb1ff8f96860904bb48`

To install version tagged as 3.1.2. This is suboptimal but will fix your dependency tree version and give you the latest webcola.

**Comment by tgdwyer** [comment]
Awesome!  Thank you @anvaka for the idiot proof instructions.  I've created an npm user: tgdwyer

@jkschneider , can you please make me owner of webcola now?

**Comment by jkschneider** [comment]
@tgdwyer you have been added as an owner.

**Comment by tgdwyer** [comment]
OK!  3.1.2 is published.  Thanks @anvaka and @jkschneider !
