### ISSUE TITLE
Difficulty of addition group area to cost()

### ISSUE THREAD

**Issue by waTeim** [tgdwyer/WebCola#131]
Would it be possible to add in the area of groups to the cost function  (leading to a tendency to form square/compact groups) or would this lead to infeasibility/non-convergence?

**Comment by tgdwyer** [comment]
There is already a property on cola.Layout called [groupCompactness](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L310-L321).  The default is a very small number (1e-6).  You can try increasing it to get more compact groups.  Making the value too high won't lead to infeasibility or non-convergence, but it may lead to some funny looking layouts :-).
