### ISSUE TITLE
d3adaptor doesn't return all events from 'tick' function for functional piping

### ISSUE THREAD

**Issue by breakingco** [tgdwyer/WebCola#132]
Hi

The ```console.log``` in this code: 

```javascript
const forceLayout = cola.d3adaptor()
  forceLayout.size([width, height])
    .nodes(nodes)
    .links(links)
    .linkDistance(300)
  var temp = forceLayout.on('tick', forceTick)
  console.log(temp);
```
...returns an object with only ```start```, ```end```, and ```tick``` properties. The original ```d3.layout.force().on()``` returns all available properties for functional piping.

Therefore the code in cola must be written with awareness of this, and with the ```tick``` event declared separately, e.g or code like this is not possible:
```javascript
const forceLayout = cola.d3adaptor()
  forceLayout.size([width, height])
    .nodes(nodes)
    .links(links)
    .forceLayout.on('tick', forceTick)
    .linkDistance(300)
```
...because ```linkDistance``` doesn't exist in the returned object. 

Thanks!

**Comment by tgdwyer** [comment]
What version are you using?

In the latest bits, the [```on``` method in ```D3StyleLayoutAdaptor```](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/d3adaptor.ts#L48-55) overrides Layout's definition to return a ```D3StyleLayoutAdaptor``` and definitely supports chaining.

**Comment by breakingco** [comment]
Ah, well this is via the custom npm module of @simontegg that I'm using; I
couldn't get it working with browserify/babel with the default github
source or npm module. It could well be fixed if the current master is more
recent than the @Simontegg fork, but I don't know how to get that working
in my current workflow. Thanks for checking :)

**Comment by breakingco** [comment]
Just to be clear though, from checking that version most of the methods
under the adaptor returned all chainable d3 methods as expected; it was
just the .on method that only returned 3 methods. But if this is fixed in
more recent versions then it's taken care of.
