### ISSUE TITLE
BUG: Constraints not respected

### ISSUE THREAD

**Issue by remram44** [tgdwyer/WebCola#133]
I have a graph in which nodes are supposed to be ordered, using left/right constraints. However some of the constraints seem to be ignored.

http://jsfiddle.net/wk2eonyw/
https://gist.github.com/remram44/6dcf334fc3cb66cc6c8b

**Comment by remram44** [comment]
If I remove the other nodes (that don't participate in the constraints: one, two, three and four), the constraints are respected.

**Comment by tgdwyer** [comment]
Minor change:

http://jsfiddle.net/wk2eonyw/1/

if you invoke the start method with numbers of iterations to run for different levels of constraints then it has a chance to satisfy your specified constraints before satisfying non-overlap constraints.  
    .start(10,10,10);
