### ISSUE TITLE
some console.asserts in rectangle.ts

### ISSUE THREAD

**Issue by timelyportfolio** [tgdwyer/WebCola#135]
I discovered these `console.assert` left in rectangle.ts.  Throughout the rest of the repo, these are all wrapped in `/* DEBUG`.  Not sure if these should be wrapped also.

https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/rectangle.ts#L283
https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/rectangle.ts#L318

Thanks so much for such a fantastic repo and interesting research!

**Comment by nchen63** [comment]
I got the same asserts. 

Mine were caused by using the avoidOverlaps(true) option without setting a width/height attribute on my nodes.

**Comment by tgdwyer** [comment]
Yes, if they fail they are almost certainly an indication that something is not set up that properly.  For that reason, I'm inclined to leave them in to help people debug their usage of the library.  Having said that, I should probably make them more informational.

**Comment by dgrisby** [comment]
I just submitted a pull request that fixes a bug that was tripping the second of those asserts. That's a good justification for keeping the asserts.

**Comment by tgdwyer** [comment]
Thanks!

On 11 November 2015 at 05:40, Duncan Grisby <notifications@github.com>
wrote:

> I just submitted a pull request that fixes a bug that was tripping the
> second of those asserts. That's a good justification for keeping the
> asserts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgdwyer/WebCola/issues/135#issuecomment-155526176>.
>



-- 
Dr Tim Dwyer BSc BCS(Hons) PhD
Senior Lecturer and Larkins Fellow
Caulfield School of Information Technology
Monash University
Australia
http://marvl.infotech.monash.edu/~dwyer/
Mobile: 0481 240 767
(from overseas: +61 481 240 767)
