### ISSUE TITLE
Debugger statement preventing V8 from optimising computeNextPosition

### ISSUE THREAD

**Issue by neil-morrison44** [tgdwyer/WebCola#138]
https://github.com/tgdwyer/WebCola/blob/master/WebCola/cola.js#L2448

Not sure how much this is affecting performance, feel free to close this if it's negligible.
This seems to be called a lot, and seems to be the only function that fails to get optimised by V8.

**Comment by tgdwyer** [comment]
Good catch!  That should not have slipped through into production code. Particularly buried in a loop like that.
It is now removed in master.
