### ISSUE TITLE
Prevent overlapping with bounding box

### ISSUE THREAD

**Issue by 4dmedia** [tgdwyer/WebCola#139]
Hello, 

I am using cola.js to prevent nodes from overlapping and also implementing a bounding box based on the method outline here: 

http://stackoverflow.com/questions/13488862/bounding-box-in-d3-js

The overlapping is prevented in the middle of the view, but as you can see in the attached screenshot, the nodes overlap once they reach the bounds.  Any ideas on how to prevent overlapping even at the bounds of the box?  

Is this possible?

![Uploading Screen Shot 2015-08-31 at 11.18.01 PM.png…]()

**Comment by tgdwyer** [comment]
Hmm.. didn't see your screen shot.

The way to do it with cola, as mentioned in [this paper]
(http://www.researchgate.net/publication/221557356_Dunnart_A_Constraint-Based_Network_Diagram_Authoring_Tool), is to create dummy variables with ideal positions at the boundaries and very high weights before passing to the VPSC solver.  I've thought about making a built in constraint for this, but you can do it at the API level by creating a dummy node for the top-left page boundary and a dummy node for the bottom right boundary.  Set each nodes "fixed" property to true and set their x and y positions at the desired page bounds.  Then create a separation constraint between each of your real graph nodes and these page bounds to keep them on the correct side of the boundary.

The nice thing about this method is that if it is impossible to fit the whole graph into the window with non-overlap constraints on, then the page bounds will stretch - which you can handle at the UI level (as per the above paper).

It should be easy, but if you get stuck let me know and I'll give you some code.

**Comment by 4dmedia** [comment]
Hey Tim, 

Thanks a lot for your in-depth response and link to the paper...I really appreciate it.  So, but have been reading up on them on the site and in your paper.  I am actually getting a bit stuck on the first part which is just creating the dummy nodes - I imagine you mean pushing 2 additional nodes to the array after the data is loaded, correct? 

I imagine I would need to generate the separation constraint array in the loop from the datasource, similar to how I generate the links array?

Can you please provide me an example of what a separation constraint would look like in this scenario? 

Sorry bout the screenshot...looks like it didn't load.  The page this is on is currently password protected, but would be happy to share it with you via email or private message.

**Comment by tgdwyer** [comment]
Here you go:

http://marvl.infotech.monash.edu/webcola/examples/pageBoundsConstraints.html

**Comment by tgdwyer** [comment]
P.S. In the end I had to make a change to the library to get the feedback to work, that is, on the example above, if you drag a node outside the box, the position of the dummy nodes is updated so that we can redraw the box stretched to contain the nodes, then see it snap back when you let go of the node.  If you want that aspect to work you'll need to get the latest version of cola.js or cola.min.js

**Comment by 4dmedia** [comment]
Thank you very much Tim!  I really appreciate this example and your help on this.  In your example, the nodes leave the box but snap back to place.  We are hoping to keep the nodes from ever leaving the box while preventing the overlap. I will try and use code snippets/principles from what you have provided to achieve this.  Thanks so much!

This is what I’m referring to (hopefully the screenshot goes through).
