### ISSUE TITLE
On .stop() a node's bounds and x, y can be contractionary

### ISSUE THREAD

**Issue by neil-morrison44** [tgdwyer/WebCola#141]
I'm getting an issue when I'm stopping the layout after a period of time, some nodes have their x and y values outside their bounds.

I think stop should probably ensure that all values are consistent?

![screen shot 2015-09-14 at 12 06 49](https://cloud.githubusercontent.com/assets/2095051/9848466/4fb2d9fe-5ad9-11e5-8584-295f3025e683.png)

In the meantime, is there a nicer way to stop the layout while preserving consistency?

**Comment by tgdwyer** [comment]
You are right that this shouldn't happen!  I had a close look at the code and did find one way that this might happen, which is if you have ```cola.Layout.handleDisconnected``` set to true (it's true by default) and the layout is already stabilized before iteration (the tick events) begin.

It seems the code that packs the disconnected components when handleDisconnected is set to true did not directly update the node bounds -  only the centre position.  This was a bug!

Please try two experiments for me:
1) try setting ```handleDisconnected(false)``` - see if the problem goes away
2) I made a fix to address the above issue.  Please try again with ```handleDisconnected(true)``` and the [latest cola.js from github](https://github.com/tgdwyer/WebCola/blob/master/WebCola/cola.js)

Thanks for reporting this!

**Comment by neil-morrison44** [comment]
Tried the first experiment, didn't fix the issue for me though it sounds similar to the case you've found.

For reference here's a JSON output of my nodes, links, groups and constraints:
https://gist.github.com/neil-morrison44/67f9af49bc957e6de10f

and the code I'm using to start the layout (as it was before adding handleDisconnected)
```
    @layout = window.cola.d3adaptor()
      .nodes(@graph.nodes)
      .links(@graph.links)
      .groups(@graph.groups)
      .constraints(@graph.constraints)
      .size([@$el.width() * 2, @$el.height() * 2])
      .linkDistance(100)
      .flowLayout("x", 200)
      .symmetricDiffLinkLengths(12)
      .avoidOverlaps(true)
      .start(9, 3, 0)
```
and then I get certain nodes having their y coordinate outside of their bounds.

I'll try your second experiment and update if that works for me

**Comment by neil-morrison44** [comment]
Just tried again using the latest cola.js, looks like the issue is fixed in that!

**Comment by tgdwyer** [comment]
OK good.  Closing this issue.  Thanks again for reporting it.
