### ISSUE TITLE
 Cannot find module './treebase'

### ISSUE THREAD

**Issue by simontegg** [tgdwyer/WebCola#146]
when I browserify index.js I get a ` Cannot find module './treebase'` error. `rbtree.js` requires './treebase' on lines 39 and 277

**Comment by anvaka** [comment]
@tgdwyer could you please republish updated module?

Looks like the currently published build to npm was not  properly generated (it has custom `require()` method in the rbtree.js file, which crashes browserify).

However if I build webcola locally, following the instructions in this repository, then the module works properly. There is no `require` in the generated file.

**Comment by tgdwyer** [comment]
OK, I've published 3.1.3
index.js includes the rbtree code now.  Does that resolve the browserify issue?
