### ISSUE TITLE
Is cola usable as a pure layout framework?

### ISSUE THREAD

**Issue by chrisber** [tgdwyer/WebCola#151]
The cola api is offering me the following constructors. (at least what typescript is showing me)
```
cola.d3adaptor()
cola.adaptor()
```
I would like to use cola only to calculate the layout positions and adding `two way binding` and events myself.
How can a I create a layout and adding nodes/edges, and updating nodes/edges? All examples I have seen so far are based on `cola.d3adaptor()`. A little help would be nice to build a hierarchical grouping layout :smile: .

**Comment by tgdwyer** [comment]
Definitely!  Have a look at these [headless tests](https://github.com/tgdwyer/WebCola/blob/master/WebCola/test/apitests.ts#L28-L74).

As in the d3 examples, simply call the ```Layout.start()``` method again after modifying the structure of the graph to update CoLa's internal state and restart the layout iterations.

**Comment by timelyportfolio** [comment]
This is a little far-fetched, but here is the code I used in `R` to pair `igraph` with `WebCola` if it helps https://github.com/timelyportfolio/buildingwidgets/blob/1dc569549fd43068972f55b942f61545c0e67b61/week46/index.Rmd.
