### ISSUE TITLE
Bounded Non-Overlap Exmaples

### ISSUE THREAD

**Issue by idibidiart** [tgdwyer/WebCola#157]
I find this example very useful as far as documentation/help goes

http://marvl.infotech.monash.edu/webcola/examples/nonoverlapping.html

But it is lacking one really critical checkbox: 'keep within canvas dimensions'

Pushing rectangles out into infinite space is easy, but how do we constrain the to stay within the canvas dimensions is not clear. Can you please add that to the example, or give us a hint? We'd be happy to send you a PR for this but I'm not sure which part of the documentation would help me discover how to do this.  Examples are great because they present code rather than textual information. It would be nice to extend the above example so we can see if Cola can do this type of constrain layout or not.

Thanks in advance.

**Comment by tgdwyer** [comment]
Hello, the way to do it is to add high-weight variables whose ideal
positions are the edge of the canvas to the vpsc solve.  This would need to
be done inside cola.vpsc.removeOverlaps(rs) - which is obviously not
intended to be user-side code. It's a great point the removeOverlaps should
really be extended to provide this functionality.

FYI: a similar idea is used in the following example, but through a much
higher level API than the vpsc functions:

http://marvl.infotech.monash.edu/webcola/examples/pageBoundsConstraints.html



On 20 February 2016 at 05:50, idibidiart <notifications@github.com> wrote:

> I find this example very useful as far as documentation/help goes
>
> http://marvl.infotech.monash.edu/webcola/examples/nonoverlapping.html
>
> But it is lacking one really critical checkbox: 'keep within canvas
> dimensions'
>
> Pushing rectangles out into infinite space is easy, but how do we
> constrain the to stay within the canvas dimensions is not clear. Can you
> please add that to the example, or give us a hint? We'd be happy to send
> you a PR for this but I'm not sure which part of the documentation would
> help me discover how to do this. Examples are great because they present
> code rather than textual information. It would be nice to extend the above
> example so we can see if Cola can do this type of constrain layout or not.
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgdwyer/WebCola/issues/157>.
>



-- 
Dr Tim Dwyer BSc BCS(Hons) PhD
Senior Lecturer and Larkins Fellow
Caulfield School of Information Technology
Monash University
Australia
http://marvl.infotech.monash.edu/~dwyer/
Mobile: 0481 240 767
(from overseas: +61 481 240 767)
