### ISSUE TITLE
Groups filling up SVG

### ISSUE THREAD

**Issue by kokster** [tgdwyer/WebCola#158]
Hi. I am using your "Small groups" example ( https://github.com/tgdwyer/WebCola/blob/master/WebCola/examples/smallgroups.html ) for a project i am currently working on. It works pretty nice, but I have one question.

In my case both the nodes and the groups are static. I would like to have the groups fill up my SVG, meaning that there is no whitespace left. I know that when you zoom in/out it is gonna get messy, but at least initially on load, is that possible?

Thank you.

**Comment by tgdwyer** [comment]
Do you mean you want to zoom-to-fit after the layout stabilizes or do you want a more compact group layout than you currently have?
