### ISSUE TITLE
Adding new groups after initial layout

### ISSUE THREAD

**Issue by cedricvidal** [tgdwyer/WebCola#162]
Hi,

I've tried modifying smallgroups sample to add a group after the initial layout but without success. Group virtual nodes and constraints seem to be computed correctly only on first layout. One can add nodes but no groups.

Am I doing something wrong or is it a missing feature ?

What's more, in order to work around that, I've tried to figure out how I could add constraints myself to reproduce the grouping but can't wrap my head around it. Could you give a glimpse into what direction to take to be able to dynamically add groups on an existing graph ?

Regards,

Cédric

**Comment by tgdwyer** [comment]
After you modify any graph elements or constraints you will need to call the [```start()```](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L476-L491) method again.  [This example](http://marvl.infotech.monash.edu/webcola/examples/browsemovies.html) shows how to add nodes and links, the procedure for modifying groups and constraints is similar.

You should probably also call  [```stop```](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L695) before mutating any of the graph element arrays on cola.

**Comment by tgdwyer** [comment]
By the way, I realise there are no really good examples of this currently.  If you make one that you are willing to share please let me know :-).

**Comment by SpyR1014** [comment]
I made a little [demo of dynamic grouping](
https://bl.ocks.org/SpyR1014/7d8ccde194ee68750b496ef70af4506b).

If I add `layout.stop()` before the group updates, the layout seems to freeze while it's becoming stable, only applying the group change once stable. In this example it works without calling `layout.stop()`.

**Comment by liuzida** [comment]
@AndrewJakubowicz I can't find you demo from your link
