### ISSUE TITLE
question: layout advice

### ISSUE THREAD

**Issue by eamonnmag** [tgdwyer/WebCola#169]
I've been playing with WebCola for some hours and I like it. But, I've been having some problems with DAGS, in particular, DAGs with a lot of node groupings happening at the bottom of the graph.

To illustrate my point, I have this graph which renders just fine.

<img width="325" alt="screen shot 2016-04-26 at 15 42 54" src="https://cloud.githubusercontent.com/assets/282396/14820143/8c099fe4-0bc5-11e6-84e1-ce5302ec9e7a.png">

But, in a more complicated graph layout, I have this.

<img width="491" alt="screen shot 2016-04-26 at 15 43 24" src="https://cloud.githubusercontent.com/assets/282396/14820157/9d8a5e48-0bc5-11e6-9661-7320a9db451d.png">

There are some edge crossings happening where I wouldn't expect them to be. So I would hope for a layout (made after some manual corrections) to look a bit more like this (although again not perfect). 

<img width="553" alt="screen shot 2016-04-26 at 15 46 05" src="https://cloud.githubusercontent.com/assets/282396/14820224/ff123b4a-0bc5-11e6-890a-911c87a55854.png">

So, in a convoluted way, what I'm asking is if there is a way to limit edge crossings because I think this would more optimally arrange the graph.

BTW, all my code is available [here](https://github.com/eamonnmag/cap-workflow-vis).

**Comment by tgdwyer** [comment]
Sorry for the slow response.  I was teaching the last few months and a lot of stuff got sidelined.  Do you have flow layout on as well?  Adding flow constraints often induces more crossings, they can be very difficult to avoid.  Have you tried using routing, as in [this example](http://marvl.infotech.monash.edu/webcola/examples/unix.html)?

Also, note the call to start can have up to three parameters which specify a number of iterations for each "stage" of layout.  If you are using constraints (such as flow layout) then putting larger numbers in these three parameters can help to untangle, e.g. 

    cola.start(20,40,50);
