### ISSUE TITLE
Jaccard distance not Jaccard index

### ISSUE THREAD

**Issue by codeout** [tgdwyer/WebCola#175]
Hi,

https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/linklengths.ts#L67

``` typescript
intersectionCount(a, b) / unionCount(a, b)
```

This doesn't look Jaccard distance but [Jaccard index](https://en.wikipedia.org/wiki/Jaccard_index).

I'd think that **distance** should be something like:

``` typescript
1 - intersectionCount(a, b) / unionCount(a, b)
```

**Comment by tgdwyer** [comment]
Good point.  Regardless of names though the calculation is what I intended, basically that things that have a lot of common neighbours need to be more spread out in order to make sufficient space for those neighbours ("cluster busting").

**Comment by codeout** [comment]
Thanks. That sounds reasonable to me.
