### ISSUE TITLE
Add D3.js v4.x compatibility

### ISSUE THREAD

**Issue by pawroman** [tgdwyer/WebCola#178]
With D3.js bumped to version 4.0 (breaking compatibility) WebCola no longer works. It would be nice if it did :)

https://github.com/d3/d3/releases

**Comment by tgdwyer** [comment]
I had a look at d3 4.1 today.  The force API is totally changed... it will take a bit of work.  On the to do list (but a ways down).  Feel free to jump in and have a go at forking a version to work with d3 4.1.

**Comment by tgdwyer** [comment]
Have a look at the [d3v4 branch](https://github.com/tgdwyer/WebCola/tree/d3v4).  It's still work in progress... but seems to work.

**Comment by gcallaghan** [comment]
@tgdwyer I see you merged d3v4. Can this be closed?

**Comment by voodoologic** [comment]
The [documentation](http://marvl.infotech.monash.edu/webcola/) makes no reference to this. :(

**Comment by Spaxe** [comment]
Echoing here, @tgdwyer can we have an up to date documentation for how to use webcola with d3 v4 & v5?
