### ISSUE TITLE
Is it possible to make different layout type on one graph?

### ISSUE THREAD

**Issue by caracal7** [tgdwyer/WebCola#185]
For example: one part of the graph with downward-pointing edges and another part is unconstrained graph...

**Comment by tgdwyer** [comment]
The [`flowLayout`](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L293) method simply traverses the edges in a given graph and creates a separation constraint over the nodes of each edge not involved in a cycle.  There is nothing stopping you creating your own separation constraints to achieve the same thing for only a part of the graph.  Of course this is a little bit less convenient than simply calling a single method.

**Comment by caracal7** [comment]
Thanks, Tim for fast answer!
I tried your way and it works exactly as I want))
