### ISSUE TITLE
Add D3.js v4.x drag group compatibility

### ISSUE THREAD

**Issue by ckathleen** [tgdwyer/WebCola#190]
Groups do not appear to be draggable with the method used in d3.v4 shown in this example https://github.com/tgdwyer/WebCola/blob/master/WebCola/examples/smallgroups.html

**Comment by costezki** [comment]
It seems that the general compatibility[ issue with D3 v4.x](https://github.com/tgdwyer/WebCola/issues/178) has to be solved first.

**Comment by tgdwyer** [comment]
Yes, I spent this afternoon heading down the rabid hole of trying to update to d3 v4s new drag event model.  I think it's just a refactoring, but transitioning is further complicated by the [typescript typings for d3v4](https://github.com/tomwanzek/d3-v4-definitelytyped) depending on typescript2 + some form of bundling for browser-side.  I think I might need to wait a little while for this one - sorry!

**Comment by tgdwyer** [comment]
Thanks to some timely work by @gcallaghan I just pushed a version to the [d3v4 branch](https://github.com/tgdwyer/WebCola/tree/d3v4) where group dragging works.
If you clone and build that branch, run a local http server and then have a look at the [smallgroups example](https://github.com/tgdwyer/WebCola/blob/d3v4/WebCola/examples/smallgroups.html) you should be able to drag the groups.
Note that I'm still messing with it and it forces an API change and most of the other examples still need fixing up.

**Comment by gcallaghan** [comment]
@tgdwyer I see you merged d3v4. Can this be closed?
