### ISSUE TITLE
The homepage for this library seems to have gone away

### ISSUE THREAD

**Issue by sharon-tickell** [tgdwyer/WebCola#200]
The homepage listed in documentation for this library ( http://marvl.infotech.monash.edu/webcola/) is no longer available. Is this a temporary thing, or has it been moved elsewhere?

**Comment by tgdwyer** [comment]
Thanks!  It's back now.

**Comment by tgdwyer** [comment]
Still down... working on it.

**Comment by colin-combe** [comment]
Was having this issue but seems its fixed now, think you can close this

**Comment by tgdwyer** [comment]
Thanks!
