### ISSUE TITLE
my nodes are off-centre with respect to their bounds - what should I do?

### ISSUE THREAD

**Issue by colin-combe** [tgdwyer/WebCola#202]
Hi,
I'm getting good results using webcola, much better than with the d3 force layout. I'm looking forward to getting further into what WebCola can do.

At the moment, I think my results are suboptimal because the bounds of my nodes are off-centre with respect their x,y coordinates. 

As background - I am changing the tool described at  https://www.ncbi.nlm.nih.gov/pubmed/25648531 to use WebCola. In a case like this: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4390258/figure/F4/ , each bar is a node and its x,y coords are the mid point of the bars, so its bounds (which contain the internal links shown as arcs) are quite a bit off-centre. The x,y coords of a node are where lines are drawn to when a node is collapsed to its circular form (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4390258/figure/F6/). 

WebCola sometimes gives results like this:
![screenshot from 2016-12-15 15 05 48](https://cloud.githubusercontent.com/assets/977607/21229128/6ae1f88c-c2d8-11e6-866e-074324bfe895.png)

I think the node that is in bar form in the screenshot is positioned slightly too high for the reason I mention. Also, I think everything's a bit off to the left for the same reason.

I have tried to figure out how to fix it, looking into the use of the setXCentre/setYCentre functions and also at how the bounds attribute of nodes gets set. But I haven't had any success - I'm not sure whats happening and there seems to be several places where the bounds get reset/updated.

What's the correct way to deal with this situation (assuming I have managed to explain my problem)?

Any help much appreciated,
best wishes,
Colin

**Comment by tgdwyer** [comment]
Are you setting the width and height of each node correctly?  Remember that webcola knows nothing about the visual that you bind it to using d3.  You have to specify the width and height properties yourself.

**Comment by colin-combe** [comment]
I believe so. 

My nodes are kind of complicated objects that can represent proteins as either circles (sequence hidden) or bars (sequence shown) - I added width and height properties to these objects that report to cola the current bounds of the node's SVG group. This appears to work and nodes are given about the right amount of space.

As I say, I think I'm getting slightly sub optimal results because the x,y coords of my nodes are not at the centre of these bounding boxes. I think changing all my code outside cola so that these coords are at the centre of this bounding box could cause quite a bit of work for me. 

Thanks for help,
c

**Comment by colin-combe** [comment]
Actually, I think I can deal with this by renaming the x and y attributes I use and and then maintaining seperate 'x' and 'y' attributes that really are the centre of the bounds.

I asked the question because I saw the the setXCentre and setYCentre functions and thought there was perhaps a built in way of dealing with this.

I'll close this - its probably not really an issue with webcola.
