### ISSUE TITLE
how to minimize render time of cola force layout.

### ISSUE THREAD

**Issue by JaishriMahajan** [tgdwyer/WebCola#206]
I tried cola with d3v4 force layout.Graph may contain thousands of nodes.I tried layout for 1000 nodes.Render time in browser is upto 68-69 seconds(2.5 times more than normal force layout).Is there any solution to minimize render time of cola.js force ?

Thanks in advance.

**Comment by JaishriMahajan** [comment]
Hi, Can you please provide any update on above issue?

**Comment by tgdwyer** [comment]
As per the note on home page: "it may be less scalable to very large graphs"
In general I find it comparable to about 300 nodes but after that you are advised to either filter your graph or stick with D3 force.
