### ISSUE TITLE
Simulation tightens with interaction

### ISSUE THREAD

**Issue by doublemarked** [tgdwyer/WebCola#214]
Hello!

Thank you very much for the excellent project! 

I've noticed something both in the examples and in my own project - when I interact with the simulation, dragging it around a bit etc, after drag and releasing 4-5 times the flexibility appears to decrease, tightening everything up. For example, check out the following demo:

   http://marvl.infotech.monash.edu/webcola/examples/alignment.html

When you first grab on to the 'a' node and wiggle it around it freely bumps into the neighboring 'b' and 'e' nodes. However, after a few cycles of click->drag->release you'll find that the 'a' node no longer comes close enough to the neighboring nodes to bump into them.

This only happens when you click and release, not if you click and hold and keep wiggling, which makes me believe it's something connected to whatever is fired off when dragging starts or stops. The end effect of this is that the "feel" of our simulation changes as the user interacts with it. 

Is this deliberate?

**Comment by tgdwyer** [comment]
Hmm, interesting.  Indeed it's not deliberate.  It seems to be running more iterations between tick events after layout converges and is restarted by a new drag... I'll have to investigate to see why.

**Comment by doublemarked** [comment]
Ok, thank you very much! I am still relatively new to working with d3 and WebCoLa, but please let me know if there's anything I can do to assist.

**Comment by tgdwyer** [comment]
Good catch!  I think this is a bug that crept in when I wrote the d3v4 adapter.  I was never explicitly stopping the d3 timer that invokes the layout iterations on layout convergence.  As a result I think every drag would start a new timer, meaning a whole bunch of layout ticks would be queued up and have to be applied before the client side tick handler was invoked.  Anyway, stopping the timer explicitly on layout convergence leads to more consistent dragging.

**Comment by doublemarked** [comment]
Excellent, thank you very much! This sounds like it may fix another quirk I saw, where some of the examples get noticeably laggy.

**Comment by doublemarked** [comment]
Hey @tgdwyer, when do you think you might republish the npm package w/ this change in place? Unfortunately it's a bit inconvenient to use this module w/o it being published because the JS build artifacts aren't committed to github.

**Comment by tgdwyer** [comment]
Done, published as v3.3.3
