### ISSUE TITLE
Some examples are not working (cola.vpsc undefined)

### ISSUE THREAD

**Issue by pembeci** [tgdwyer/WebCola#217]
See for instance:

- [Non-overlapping](http://marvl.infotech.monash.edu/webcola/examples/nonoverlapping.html)
- [Metabolic Pathway: Sucrose Breakdown](http://marvl.infotech.monash.edu/webcola/examples/sucrosebreakdown.html)

Both FF and Chrome reports `cola.vpsc` is undefined.

**Comment by maxint137** [comment]
It appears that the vpsc module was removed in December'16 by `Refactor: Make npm/commonjs friendly` (30a4bbd081675cbd3b9b9ec20941e5ba12aae832). Right now classes defined in that module are directly accessible (i.e. `cola.Rectangle`). My understanding that it's a simple fix, similar to the fixes that were done to [browsemovies.html](https://github.com/tgdwyer/WebCola/commit/5be3d627386b46faf9802bca10459580cf6dee8c#diff-df126270feda84ac432e9b842cf2e234) in 5be3d627386b46faf9802bca10459580cf6dee8c.

**Comment by tgdwyer** [comment]
- non-overlapping fixed now.
 - metabolic pathway was already fixed but the bits on my server were out of date

**Comment by pembeci** [comment]
Thanks @maxint137  and @tgdwyer.
