### ISSUE TITLE
is there a way to stop this (image attached)?

### ISSUE THREAD

**Issue by colin-combe** [tgdwyer/WebCola#233]
Hi,
I have a fairly simple (8 node) network which I struggle to get to layout with no lines crossing, though such a solution is possible. Cola is not the only layout algorithm I've tried that doesn't get it right. (d3 force layout is sometimes optimal, sometimes not; the more stable/reproducible cola layouts are consistently sub-optimal with the crossed lines in the middle.) Image below:
![hemoglobin](https://user-images.githubusercontent.com/977607/27793544-69afbdb2-5ff6-11e7-8867-6b13e08f770d.png)
Does anyone know of a way to avoid this, or am I asking the impossible?

cheers,
colin

**Comment by tgdwyer** [comment]
A common strategy to getting better untangling is to layout part (or a backbone, or just the biconnected components) of the network first - then introduce the remain nodes, perhaps incrementally.

In this example, the one biconnected component is the subgraph containing only the four _human nodes.  If you give just this part to cola you will get a nice neat square every time.  You would then add the remaining nodes, with starting positions set the same as their already positioned neighbours (the _human nodes).  Cola will then pop them out into the nice neat star arrangement you want.

This kind of "batch procedure" is precisely the sort of thing I would like to code into the batch.ts module - but it's a work in progress.

**Comment by tgdwyer** [comment]
Here's a more general technique that could built fairly easily over cola for better untangling.  It's a very simple repeating matching process to simplify the graph into a number of levels of detail:
https://link.springer.com/chapter/10.1007/3-540-44541-2_17

From this multilevel hierarchy, one would pass successively more detailed graphs into cola until all nodes are present and laid out.

**Comment by colin-combe** [comment]
Thanks for these ideas,
colin
