### ISSUE TITLE
import cola from 'webcola' not working

### ISSUE THREAD

**Issue by namwkim** [tgdwyer/WebCola#235]
Not critical. Just reporting this. 

import cola from 'webcola' does not seem to work for some reason (i.e., cola is null)

Not sure what's changed.

But I can do

import {d3adaptor, Layout} from 'webcola', which is perfectly fine though.

I am using es6 with webpack & babel. The version is 3.3.6.

**Comment by ViggoV** [comment]
You can try `import * as cola from 'webcola'`. Then you should be able to access `cola.d3adaptor` and `cola.Layout`. Same as d3.

**Comment by salmankazmi** [comment]
> You can try `import * as cola from 'webcola'`. Then you should be able to access `cola.d3adaptor` and `cola.Layout`. Same as d3.

I did this: `import * as cola from 'webcola';` in my Angular2 app. It says: `"ReferenceError: d3 is not defined`. Though I have the d3 dependency already present.
