### ISSUE TITLE
How to get bounding box values for the layout?

### ISSUE THREAD

**Issue by ancashoria** [tgdwyer/WebCola#251]
Hi,
I have an SVG in which I render the cola nodes and I'd like to know when nodes overflow the current SVG size and increase it. To do this, I need to know the bounding box values of the nodes, basically the width and height of the rectangle that contains all the nodes.

Can I get this data from cola, or do you suggest another approach to accomplish this?

**Comment by tgdwyer** [comment]
Nothing built in I'm afraid.  The following is from one of the examples:
```
function graphBounds() {
    var x = Number.POSITIVE_INFINITY, X = Number.NEGATIVE_INFINITY, y = Number.POSITIVE_INFINITY, Y = Number.NEGATIVE_INFINITY;
    nodesLayer.selectAll(".node").each(function (v) {
        x = Math.min(x, v.x - v.width / 2);
        X = Math.max(X, v.x + v.width / 2);
        y = Math.min(y, v.y - v.height / 2);
        Y = Math.max(Y, v.y + v.height / 2);
    });
    return { x: x, X: X, y: y, Y: Y };
}
```
