### ISSUE TITLE
some examples seems broken 

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [tgdwyer/WebCola#269]
Some example like https://ialab.it.monash.edu/webcola/examples/onlinebrowse.html seem broken.

I see nothing and I get in the console: "TypeError: d3.behavior is undefined"

**Comment by jaminellis** [comment]
Yes - seem to be a few files missing in the repo.

**Comment by namwkim** [comment]
this one is not working too

https://ialab.it.monash.edu/webcola/examples/powergraph.html

**Comment by cc-stjm** [comment]
https://ialab.it.monash.edu/webcola/examples/unix.html is also broken. Makes it very hard for me to follow as a potential new user.

**Comment by tgdwyer** [comment]
Fixed. Thanks for reporting!  I don't have any automated tests for these so they easily bitrot.
