### ISSUE TITLE
Dragging groups

### ISSUE THREAD

**Issue by YoannBuch** [tgdwyer/WebCola#43]
Hi Tim,

It 's not possible to drag groups the same way as nodes: 
http://marvl.infotech.monash.edu/webcola/examples/smallgroups.html

Any reasons why it's not supported? 

What could be a workaround? I'm thinking to do something like: translating the group and descendant groups/nodes when user drags the group. I'd probably need to set the nodes as fixed until dragging is done.

Thanks for great work

**Comment by tornaydo** [comment]
Hi Yoann,

Did it work ? If it did then pls can you past  code sample :)

Thanks.

**Comment by tgdwyer** [comment]
Groups are now draggable!

http://marvl.infotech.monash.edu/webcola/examples/smallworldwithgroups.html
http://marvl.infotech.monash.edu/webcola/examples/smallgroups.html

**Comment by astefanutti** [comment]
Very cool!

**Comment by timelyportfolio** [comment]
:100:

**Comment by YoannBuch** [comment]
Just noticed that email, really cool, thank you!!
