### ISSUE TITLE
Publish as a npm module

### ISSUE THREAD

**Issue by simontegg** [tgdwyer/WebCola#44]
Publishing WebCola as a npm module would make it available in the [browserify](http://browserify.org/) ecosystem and allow sever-side rendering of graphs.

**Comment by aspiers** [comment]
This appears to have been closed without resolution?

**Comment by aspiers** [comment]
@simontegg Are you able to submit a pull request for this?

**Comment by simontegg** [comment]
Thanks for the reminder @aspiers. I have a pull request open here https://github.com/tgdwyer/WebCola/pull/72 which I can put some work into to get ready with feedback
I'm actually using my fork as a npm module with browserify and it works great!

However, I did have to shoe horn it into npm compatibilty and made [some significant changes](https://github.com/tgdwyer/WebCola/pull/72#issue-55685480) to the project setup. 

These changes make it hard for a maintainer to simply look at the diff on github and give approval or not. You may have a simpler solution! 

WebCola is an awesome library, but its quite chunky and a bit intimidating to modify in Typescript. I found the Typescript module system did not map cleanly to the common js module system, and I wonder what the best practice is here?

**Comment by breakingco** [comment]
AHA!

This is really important functionality for newer developers who basically only work within a module requiring environment. I have been unable to get WebCola working at all through the standard browserify/babel pipeline. Had just given up and decided that I just couldn't use it and was lodging an issue when I saw this and added simontegg's npm package instead. Success!

Although one major thing - the index.js doesn't require the d3adaptor, which I'd imagine would be the bit used by a significant number of folks coming to this. Adding d3adaptor: ```require('./lib/d3adaptor')``` to the cola object in index.js fixed this.

**Comment by tgdwyer** [comment]
Thanks all, particularly @simontegg and @aspeers.  I have no idea how to prepare an npm module so I appreciate your support.  I'm happy to merge the pull request as soon as you think it is ready.

**Comment by worldsayshi** [comment]
For anyone else ending up here being a bit confused why it looks unresolved. Resolution is here: https://github.com/tgdwyer/WebCola/pull/108
