### ISSUE TITLE
Horizontal/Vertical distribution constraints?

### ISSUE THREAD

**Issue by jazzido** [tgdwyer/WebCola#47]
Is it possible to specify vertical or horizontal distribution constraints? 

I've noticed that is possible to do it in Dunnart, but couldn't find a way to emulate that behaviour with WebCola.

Thanks!

**Comment by tgdwyer** [comment]
Your proposed API looks good.  You could also achieve the same thing with the existing alignment constraint API and precomputed offsets for each node:
```json
{
	"type":"alignment",
	"axis":"x",
	"offsets":[
	 {"node":0, "offset":0},
	 {"node":1, "offset":42},
	 {"node":2, "offset":84}]
}
```

Obviously, this is less friendly than your distribution.  Are you offering to implement the distribution constraint API?  If so, you should look at rectangle.ts where we define a Projection class whose constructor converts the alignments to separation constraints  (see the createAlignment method).  We'd need to do the same thing for distributions.

**Comment by aspiers** [comment]
See also #56.

**Comment by aspiers** [comment]
Whilst we're talking about the constraints API, I've noticed two inconsistencies:

1. `left` and `right` are used as the constraint attributes even when the presence of `axis: 'y'` changes them to actually mean top and bottom.
2. `type: "alignment"` but not `type: "gap"`

**Comment by tgdwyer** [comment]
1. From the solver's point of view, it is talking about which variable is on the left and right side of the less-than.  I agree unfortunately that this is confusing when you start thinking about axes.  
2. see `rectangle.ts`:  `type=='alignment'` causes it to be treated as an alignment constraint with a list of per-node offsets, everything else is treated as a separation constraint with a `left` and `right`.

**Comment by aspiers** [comment]
I see.  #56 should cover the task of clarifying these points.

**Comment by aspiers** [comment]
I've created https://github.com/tgdwyer/WebCola/wiki/Constraints as a stub page for proper constraints documentation.
