### ISSUE TITLE
Preventing link overlap

### ISSUE THREAD

**Issue by bunkat** [tgdwyer/WebCola#50]
Is there any way to prevent link overlap using WebCola?  I have a graph set up that uses `x` and `y` alignment constraints to arrange the nodes and am able to achieve the following:

![image](https://cloud.githubusercontent.com/assets/665885/5620075/074ace00-94dd-11e4-929e-fc0a33a0253f.png)

I'm now trying to get rid of the last overlapping links and can't figure out how to push the node up into the new position to accomplish this.  Is this possible without hard coding it?

**Comment by aspiers** [comment]
I have a similar challenge, and I have just found https://github.com/cpettitt/dagre which seems perfect for this - it uses a bunch of different layout algorithms to achieve an [optimised graph layering](http://en.wikipedia.org/wiki/Layered_graph_drawing) and then provides the layout numerically but still leaves the rendering up to you.  The particular problem highlight above corresponds to the fifth step in the algorithm described in that Wikipedia article: "The vertices within each layer are permuted in an attempt to reduce the number of crossings among the edges connecting it to the previous layer."  In your case, each layer is aligned vertically in a column.  I am going to try it out very soon!

**Comment by tgdwyer** [comment]
Yes, for layered layout of small graphs "sugiyama" layout algorithms such as Dagre work well.

**Comment by aspiers** [comment]
I've tried it out today, but without much success so I'm probably doing something wrong.  Here's my code which feeds the graph to dagre, asks it to build a layout, and then uses the results to build cola alignment and separation constraints by grouping nodes into rows by their y coordinates, aligning all nodes in the same row, and preserving row ordering:

* https://github.com/aspiers/git-deps/blob/master/html/js/git-deps-layout.js

However I'm experiencing several problems:

* The separation constraints intended to order rows vertically according to dagre's recommendations are not working (see #60 and #61)
* Alignment within a row leaves webcola zero flexibility for reordering nodes within a row (see #62)
* No way of using dagre's recommendations for ordering within a row (see #63)
* The initial layout often starts with nodes overlapping (see #64)
* Link lengths are not flexible enough (see #65)

Advice hugely welcome!

**Comment by bunkat** [comment]
I couldn't get Dagre to work very well for me at all.  The constraints don't seem to do much of anything and sometimes it produces graphs that are totally nonsensical (nodes were basically randomly laid out with missing connections).  That really wasn't an option when presenting graphs to customers, I have to always be able to present something that wasn't horrible.

I ended up writing my own implementation of the Sugiyama layout that uses a genetic algorithm approach to minimize edge crossings.  It's tailored to the particular type of graph I needed to produce (horizontal, grid layout) but it ended up working out quite well.  Here is how my original graph gets laid out:

![image](https://cloud.githubusercontent.com/assets/665885/5712964/a695b9fa-9a6b-11e4-8ff3-da70c94ed00d.png)

**Comment by aspiers** [comment]
In the last 24-48 hours I've actually solved pretty much *all* of the problems I listed above.  The breakthroughs came from realisations which are documented in #62 and #66, as well as the discovery of some subtle but significant bugs in my code.  Now that I have webcola honouring the layout suggested by Dagre, it's looking very nice indeed, even when the graphs get hairy.  I'm about to record a YouTube demo, but here's a sneak preview screenshot!

![screenshot from 2015-01-13 01 48 25](https://cloud.githubusercontent.com/assets/100738/5714844/5a8b18b0-9ac6-11e4-8459-6a9832a31288.png)

**Comment by tgdwyer** [comment]
Great!

**Comment by aspiers** [comment]
@bunkat Any chance you could share your genetic algorithm code?

**Comment by j1mie** [comment]
Hi @bunkat - I've a similar use case for a graph (horizontal, grid layout) and was wondering if you share any direction or advice for how to get started with this. Thanks! 🎉
