### ISSUE TITLE
meaning of VPSC not documented

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#52]
I see some references to it but no explanation what it means!  Would be great to document this ... thanks!

**Comment by tgdwyer** [comment]
You are right, this is poorly documented on the webpage.  VPSC is our custom solver for projection subject to separation constraints (it's a particular quadratic program).  It is used by the layout process to efficiently satisfy constraints like alignment, containment and non-overlap while reducing the overall layout stress.  It is more thoroughly described in the following papers:

http://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=cOEUhBAAAAAJ&citation_for_view=cOEUhBAAAAAJ:d1gkVwhDpl0C

http://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=cOEUhBAAAAAJ&citation_for_view=cOEUhBAAAAAJ:9yKSN-GCB0IC

I will try to put some blurb about this somewhere.  Where in particular would you like to see it better documented?  E.g. in the source, on the home page, in the wiki?

**Comment by aspiers** [comment]
Ah, I see - thanks!  I guess the wiki would be a good place for it, with a link from the homepage.

I've noticed a few other gaps in the documentation (that is, even when counting the very helpful examples as documentation) - I hope it will be useful if I highlight them by filing an issue for each one.

**Comment by tgdwyer** [comment]
Please do raise issues when you see a gap.  Feel free to add to the wiki as you figure stuff out too :-)

Thanks!

**Comment by tgdwyer** [comment]
Made a rather minimal wiki page about VPSC [here](https://github.com/tgdwyer/WebCola/wiki/What-is-VPSC%3F).

One day I'll organise this into something resembling an actual document.

**Comment by aspiers** [comment]
Thanks - it's a good start ;-)
