### ISSUE TITLE
Making threshold configurable

### ISSUE THREAD

**Issue by qinfchen** [tgdwyer/WebCola#53]
Threshold for alpha is set to 0.01 currently, but some animations in the examples still end abruptly. Is it possible if we can make it configurable when a new adaptor is created?

Thank you for this awesome library

**Comment by tgdwyer** [comment]
there is already a setter on adaptor called convergenceThreshold, does this work for you?

**Comment by qinfchen** [comment]
Yes, that works. Thanks
