### ISSUE TITLE
flowLayout question

### ISSUE THREAD

**Issue by qinfchen** [tgdwyer/WebCola#55]
Is there way to force all source nodes to be on the same level? 
http://jsfiddle.net/rxyqg4r3/1/

**Comment by aspiers** [comment]
Yes, use [alignment constraints](http://marvl.infotech.monash.edu/webcola/examples/alignment.html).

**Comment by tgdwyer** [comment]
http://jsfiddle.net/rxyqg4r3/4/

**Comment by qinfchen** [comment]
Thanks guys!
