### ISSUE TITLE
clarity around versioning

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#58]
Both `package.json` and `bower.json` refer to version 0.1.0; however `npm info` reports that 0.1.0 and 0.1.1 are both available, and `bower info` reports that the only versions available are 3.0.0 and 3.0.1.  And on top of that of course we have `cola.v[1-3].min.js` in the actual repo.

So what is the truth, and what is the strategy around versioning?  I would strongly recommend adopting [SemVer](http://semver.org/) best practice if possible.  If v1, v2, and v3 are considered "major" releases which contain API changes then they would become the first digit in the SemVer version string (which at a guess may explain the bower 3.0.x series mentioned above?)  In that case I think it would be much cleaner to have a git branch per major release, e.g. `v1`, `v2`, and `master` for v3.  Or if the API has already been changed in git since v3 then the next release would be 4.x.y, in which case there would also be a `v3` branch and `master` would be for 4.x.y development.

This approach is consistent with widely adopted best practices, and would make it very easy to effectively distribute releases via `npm` and `bower`.  In particular it would solve the current issue where there are multiple releases within any single checkout but the `main` entry point in `package.json` and `bower.json` can only point to one of them.

Does that make sense?  Thanks for listening!

**Comment by tgdwyer** [comment]
argh... I guess we're getting to the point where we need to take better care of versions.  I've never managed an npm or bower package before so I appreciate the guidance on best practice.  I guess we should freeze the current codebase at v3 and start v4 as a devel branch as you suggest.  Any tips on how to do this properly with npm, bower? Not to mention git for that matter... should I fork v4 as a new branch?

Thanks!

**Comment by aspiers** [comment]
Don't panic ;-)  As a fairly heavy git user (and developer) I'm pretty confident I know a good way forward, which also happens to be the most common approach I've seen in the industry:

* Create at least one stable `v3` branch, and possibly for `v2` and `v1` too if you want.
* Keep `master` for `v4` (i.e. don't create a `v4` branch until 4.x is actually released and you want to start work on v5)
* On each branch, delete any files which don't relate directly to that version, e.g. on the `v3` branch, delete `cola.v1.min.js` and `cola.v2.min.js` and so on.
* On each branch, ensure that the `"main"` attribute in `package.json` and `bower.json` points to the right `.min.js` file.
* (Optional but recommended) Drop any versioning from the filenames, e.g. (assuming there's now only one `.min.js` in each branch):

        for branch in v{1..3} master; do
          git checkout $branch
          cd WebCola
          git mv cola.v?.min.js cola.min.js
          git commit -m'drop version-specific naming from .min.js file'
        done

    This is recommended because it maximises the benefit of doing certain cross-release operations in git, such as `git diff-tree` and `git blame`.

**Comment by qinfchen** [comment]
I've created a pull request for the right version in bower.json https://github.com/tgdwyer/WebCola/pull/67
