### ISSUE TITLE
some constraints sometimes get ignored

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#61]
In my downward-facing dependency graph, I have alignment constraints forcing each node to a certain row (as ordained by the very nice [dagre layout engine](https://github.com/cpettitt/dagre/)), and separation constraints which order the rows (also dictated by dagre).  

(BTW there is only one separation constraint for each pair of rows because I didn't see the need for more than that and assumed it would probably reduce the number-crunching required.  Let me know if that's wrong.)

However when adding nodes to the graph, sometimes rows get inverted so that some of the arrows point up when they should really be pointing down.  Calling 

    d3cola.start()

repeatedly will flip them between the right way and the wrong way.  This feels like a bug to me but I appreciate it might be difficult to pin down without a minimal reproducible case, which I'll try to find time to provide.  But in the meantime, does this ring any bells, or is there a chance I've done something wrong?

Here's the bug in my project:

https://github.com/aspiers/git-deps/issues/21

Thanks!

**Comment by aspiers** [comment]
I think this *might* have been a bug in my code.  I've revamped the constraint generation code and it seems OK now.

**Comment by aspiers** [comment]
Nope, still broken :-(

**Comment by aspiers** [comment]
Here's a minimal test case: http://jsfiddle.net/aspiers/oya43Luv/embedded/result/

**Comment by tgdwyer** [comment]
sorry for the slow reply (lots going on at the moment).  I think what you have done here is created a cycle in the constraint graph.  Even though a feasible solution exists (because you are using negative gaps), the result is going to be unpredictable.  Really, a better way to keep two nodes (a and b) within a maximum band, would be to add additional dummy nodes (d1 and d2) to the graph (that you don't render).  Constrain these dummy nodes to be a fixed distance apart with an equality separation (e.g. d1.y + space = d2.y).  Then add inequalities: a.y > d1.y, a.y < d2.y, b.y > d1.y, b.y < d2.y.

We do something similar (but at a lower level) for group boundaries.

**Comment by aspiers** [comment]
Oh you mean there's a cycle caused due to having both `a.y + c1 < b.y` and `b.y + c2 < a.y` ?  So these constraints are being considered as sort of directional, like a dependency graph, where the ordering is used to find the solution?  That would make sense.

Cunning idea regarding dummy nodes; only problem might be that this could substantially increase the number of nodes and constraints, which could impact performance of both webcola and the browser rendering? Although if the dummy nodes are invisible, one would hope the latter would not be impacted too much...

**Comment by gordonwoodhull** [comment]
It surprises me that even if the constraints are in different axes, they can still create a cycle.

I started building a simple constraint checker in [dc.graph.js](https://github.com/dc-js/dc.graph.js) and it helped me solve some constraints being applied inconsistently.  One problem with integrating a checker into WebCola is that the context is lost by that point, e.g. VPSC does not even have the node indices but it's more helpful to describe the cycles using node names. 

Maybe we could annotate the constraints with some debugging metadata? Or are there more serious problems that I've forgotten?
