### ISSUE TITLE
alignment inequality constraints

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#62]
I think my dependency graph would get the best results if the grouping of nodes with the same rank/degree into rows was done not with exact (i.e. equality) alignment constraints, but with inequality constraints, i.e. "keep the y-coordinates of these nodes within 50px of each other".  Is that possible or easy to implement?  Thanks!

**Comment by aspiers** [comment]
I think I have just figured out a way to do this, but it was not particularly obvious, which strengthens my suggestion that #56 should be reopened.  As [the webpage](http://marvl.infotech.monash.edu/webcola/) says:

    {"axis":"y", "left":0, "right":1, "gap":25}

is converted into:

    graph.nodes[0].y + 25 <= graph.nodes[1].y

meaning that the node centres must be at least 25 pixels apart.  However AFAICS it is also possible to specify:

    {"axis":"y", "left":1, "right":0, "gap":-35}

i.e.

    graph.nodes[1].y - 35 <= graph.nodes[0].y

which is equivalent to:

    graph.nodes[0].y + 35 >= graph.nodes[1].y

So combining these should ensure the node centres are always between 25 and 35 pixels apart.  Furthermore, if the same constant was used in both constraints, then the two inequalities combine to achieve an equality, e.g.

    graph.nodes[0].y + 25 == graph.nodes[1].y

However I think it would be far better for the non-mathematicians if the API was extended to make this more intuitive, e.g.

    {"axis":"y", "left":1, "right":0, "min_gap":25}
    {"axis":"y", "left":1, "right":0, "max_gap":25}
    {"axis":"y", "left":1, "right":0, "exact_gap":25}

**Comment by aspiers** [comment]
I've created https://github.com/tgdwyer/WebCola/wiki/Constraints as a stub page for proper constraints documentation.

**Comment by tgdwyer** [comment]
thanks!  If no body beats me to it, I will eventually put something in there :-).
