### ISSUE TITLE
specify starting position hints for nodes?

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#63]
As already mentioned I'm using dagre to calculate a sensible ordering of rows and nodes within rows.  How can I use the node positions dagre calculates as starting points for cola's iterations?

**Comment by tgdwyer** [comment]
if you set node.x and node.y before calling start() they will be taken as the starting positions

**Comment by aspiers** [comment]
Oh, thanks!  I already had a guess that the solution required setting `x` and `y` on the data object, not the node:

* https://github.com/aspiers/git-deps/blob/master/html/js/git-deps-graph.coffee#L204

So that explains why it doesn't work - but it doesn't explain why `x` and `y` already existed on the node (and they must have done, otherwise the above code would cause an error).

**Comment by tgdwyer** [comment]
if it doesn't find existing x and y attributes on the nodes, it creates them (placing the nodes in the middle of the specified canvas size.  For better or worse, I'm following d3 force in this.

**Comment by aspiers** [comment]
Still doesn't make sense to me, because the above code is called *before* `start()` is ever called.

**Comment by tgdwyer** [comment]
I'm pretty sure that there's nothing in cola to set ```x,y``` before ```start()``` is called.  Did you figure this out already?  I'd like to close the issue and clean house a bit.

**Comment by aspiers** [comment]
No, I didn't figure it out; AFAIK it's still an issue. I'll try to revisit soon.

**Comment by tgdwyer** [comment]
I think there must be some confusion here.  To sum up:
if no x and y coordinates are specified on nodes at start up time, cola creates them, defaulting to the middle of the canvas specified by [Layout.size()](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L285-L297).
If x,y is specified on each node it is taken as starting position.  I use this functionality frequently and it's also regression tested in the unit tests.
Closing this issue now but feel free to reopen if you find another problem or need further clarification.
