### ISSUE TITLE
confusion over link lengths

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#65]
Ideally I could specify a minimum, maximum, and ideal length for links to cola.  I'm not really clear on to what extent that's currently possible.  The homepage says:

> symmetricDiffLinkLengths(5) computes ideal lengths on each link to make extra space around high-degree nodes, using 5 as the basic length.

What is the basic length exactly?  What units is it in?  Presumably not pixels, because 5 pixels would be an incredibly short link in most circumstances.  And how is `jaccardLinkLengths` different?

I've looked at the source code behind these functions and can understand the maths, but without reading a whole bunch of research on graphs I don't have much of a clue how that would impact graph layout.  

And then there's http://marvl.infotech.monash.edu/webcola/examples/unix.html which says:

> In particular, the call to flowLayout causes all edges not involved in a cycle (strongly connected component) to have a separation constraint generated between their source and sink, with a minimum spacing set to 150. Specifying the 'x' axis achieves a left-to-right flow layout. The default is top-to-bottom flow layout (i.e. 'y'). You can also specify a function as the second argument to flowLayout that returns different separations for each edge. Specify a different minimum as a second parameter to flowLayout.

So it is possible to set a minimum, but only if you're using `flowLayout`? (which I am).  What does "different minimum" mean here exactly?  I don't understand what the last sentence is saying.

Thanks for bearing with my stupid questions!  Whatever I try, I just can't yet persuade webcola to automatically converge on decent layouts :-/

**Comment by aspiers** [comment]
I just made an interesting discovery.  Normally nodes/links/constraints are set first, and then layout options, e.g. [this example from the homepage](http://marvl.infotech.monash.edu/webcola/):

```js
d3cola
    .nodes(graph.nodes)
    .links(graph.links)         
    .constraints(graph.constraints)
    .symmetricDiffLinkLengths(5)
    .avoidOverlaps(true)
    .start(10,15,20);
```

However if nodes/links/constraints get set ***after*** the layout options, link lengths are infinitely extensible:

```js
d3cola
    .nodes(graph.nodes)
    .links(graph.links)         
    .constraints(graph.constraints)
    .symmetricDiffLinkLengths(5)
    .avoidOverlaps(true)
    .start(10,15,20);
```

See http://jsfiddle.net/aspiers/2xj2u93e/15/ for a demo.

**Comment by tgdwyer** [comment]
interesting.

symmetricDiffLinkLengths call a function immediately that computes a length for each link.  Thus, if no links are specified at the time then nothing happens.  I guess instead it could simply choose a function to be applied later from start().  I'll ponder this for a bit.

regarding the difference between symmetric and jaccard, they both follow basically the same idea.  Basically, choose an ideal length for a link between nodes a and b based on how many of the neighbours of a and b are common.  The idea is to make more space around hub nodes.

As you can see from the source, however, the calculation is slightly different: jaccard is based on the ratio of neighbour intersection count and union count, while symmetric is based on the difference.

Which works better?  I don't really know that one wins absolutely.  I haven't exhaustively trialed them.

**Comment by aspiers** [comment]
OK, thanks for the info!  As soon as this is documented on the wiki or wherever (by you, me, or some other kind soul ...) I think we can close this issue. Until then we probably shouldn't expect others to use this issue tracker as a knowledge base ;-)

**Comment by tgdwyer** [comment]
I made [some documentation on the wiki](https://github.com/tgdwyer/WebCola/wiki/link-lengths).  So I'll close this issue now.  I'm slow, but please do keep pushing me to create such docs  and we'll get there in the end :-)

**Comment by tgdwyer** [comment]
P.S. I've just pushed a changed to adaptor.js that makes the jaccard/symmetric link length calculation lazy.  I.e. actual computation of these is now delayed until the start() function.  Thus, the original issue you raised about calling symmetricDiffLinkLengths before assigning the links will no longer occur.

**Comment by aspiers** [comment]
Excellent thanks!  Although I actually liked the fact that it was possible to have infinitely extensible links.  Maybe that could be reintroduced via an explicit `unlimitedLinkLengths()` function?
