### ISSUE TITLE
no way to specify unordered minimum separation constraints

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#66]
The trick I described in #62 seems to work nicely in the case where an asymmetric constraint (i.e. ordering of the two nodes along an axis) is required.  However it does not let you specify constraints like:

* ~~"keep these nodes' x coordinates within 100px of each other, but I don't care which way round they go"~~ (**UPDATE**: it *is* possible - see below)
* "keep these nodes' x coordinates at least 100px apart, and I don't care which way round they go"

That would also be very useful.

**Comment by aspiers** [comment]
Hmm, upon further thought, the trick **can** be used to specify the first of these two unordered constraints!

    [
        {"axis":"x", "left":0, "right":1, "gap":-30},
        {"axis":"x", "left":1, "right":0, "gap":-30}
    ]

translates to:

    graph.nodes[0].x - 30 <= graph.nodes[1].x
    graph.nodes[1].x - 30 <= graph.nodes[0].x

The second of these can be rewritten as:

    graph.nodes[1].x <= graph.nodes[0].x + 30

which combines with the first one to give

    graph.nodes[0].x - 30 <= graph.nodes[1].x <= graph.nodes[0].x + 30

in other words, the node with index `1` is within 30 pixels of the node with index `0`, but on either side!

Unfortunately the same trick doesn't work for requiring a minimum separation on either side:

    [
        {"axis":"x", "left":0, "right":1, "gap":30},
        {"axis":"x", "left":1, "right":0, "gap":30}
    ]

results in

    graph.nodes[0].x + 30 <= graph.nodes[1].x <= graph.nodes[0].x + 30

which has no solutions - we'd need to be able to require satisfying either one constraint or the other for that to work, not both.  But nevertheless this is good news!

**Comment by qinfchen** [comment]
Thank you for sharing this. I was also struggling with layered layout.

**Comment by qinfchen** [comment]
Here is lower and upper bound case
```javascript
[
    {"axis":"x", "left":0, "right":1, "gap":30},
    {"axis":"x", "left":1, "right":0, "gap":-60}
]
```
result in
```javascript
graph.nodes[0].x + 30 <= graph.nodes[1].x <= graph.nodes[0].x + 60
```

**Comment by aspiers** [comment]
No, that doesn't work at all because there are no solutions to that inequality.  Both constraints ask for a minimum gap of 30 but they ask for opposite orders.  You can't have both.

**Comment by aspiers** [comment]
Just realised that what I'm asking for wouldn't allow dragging to reorder the two nodes relative to each other.  Hmm.  Could still be useful though, when layouts are informed by dagre or similar.

**Comment by tgdwyer** [comment]
nice trick with the negative gaps.

regarding the second point, we cannot do disjunctions through static separation constraints.  However, if you give the nodes a width and height and then turn on non-overlaps cola will dynamically generate the separation constraints to keep the nodes apart, choosing to create the separation constraint that gives the least overlap.  Does this work for you?

**Comment by aspiers** [comment]
I already had `avoidOverlaps` on but it hadn't occurred to me that increasing the width would effectively achieve this.  So yes I guess this probably does solve it - again, best to leave the issue open until it's documented!  Thanks!

**Comment by aspiers** [comment]
I guess you disagreed with my last point "best to leave the issue open until it's documented" for some reason.  I've created https://github.com/tgdwyer/WebCola/wiki/Constraints as a stub page so that users have more chance of finding the documentation they need.
