### ISSUE TITLE
what does the tick event handler do exactly?

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#69]
I can't see any documentation for the `tick` event.  It seems to run when calling `start()` and also when nodes are dragged around - is that right?  Is it called once per iteration within the `start()` parameters?  And are the `start()` parameters reused to re-iterate after every drag event?

Thanks!

**Comment by tgdwyer** [comment]
look at adaptor.js

`start()` invokes `adaptor.resume()` which invokes `adaptor.alpha` which, when called the first time, calls `kick` to set up a d3 timer to repeatedly invoke `adaptor.tick()`.

`adaptor.tick()` then applies an iteration of layout and notifies anybody listening for `tick` events.  This gives those listeners a chance to update their visuals to reflect the updated layout.

**Comment by aspiers** [comment]
Thanks.  Another good candidate for a wiki page :)

**Comment by aspiers** [comment]
IMHO would have been better to copy the info to the wiki *before* closing, so that it doesn't just get buried here and forgotten about - but to prevent that happening I just copied it:

https://github.com/tgdwyer/WebCola/wiki/tick-handler

**Comment by tgdwyer** [comment]
You're right, I should have put something on the wiki before closing this.  Thanks for doing that for me!

**Comment by teone** [comment]
Is there any way to have a behavior that is similar to the d3 one? I don't see any force simulation (I mean nodes appearing in a position and then moving) happening, is this the expected behavior?

**Comment by marhyno** [comment]
could there be any better explanation of this ?
