### ISSUE TITLE
cola.v3.min.js has wrong sourceMappingURL

### ISSUE THREAD

**Issue by aspiers** [tgdwyer/WebCola#70]
The last line of http://marvl.infotech.monash.edu/webcola/cola.v3.min.js is:

    //# sourceMappingURL=WebCola/cola.v3.min.map

but this resolves to http://marvl.infotech.monash.edu/webcola/WebCola/cola.v3.min.map which gives a 404.  The correct link is http://marvl.infotech.monash.edu/webcola/cola.v3.min.map, therefore the last line of http://marvl.infotech.monash.edu/webcola/cola.v3.min.js should be:

    //# sourceMappingURL=cola.v3.min.map

**Comment by tgdwyer** [comment]
fixed

**Comment by qinfchen** [comment]
My project uses bower to install the webcola package and it is complaining that the map file could not be found. Can we create a min file that does not have the map url? I can always build a unminified version from this repo.

**Comment by aspiers** [comment]
Related to #44?

**Comment by derekcicerone** [comment]
The bower issue appears to be unrelated to #44. The issue seems to be that the source map files are not included in the bower distribution so the source map comment has no file to reference. This seems like a separate issue from this issue as well.

**Comment by rbruskiewich** [comment]
The http://marvl.infotech.monash.edu/webcola/cola.v3.min.map file seems missing?
