### ISSUE TITLE
computeDerivatives stuck in an infinite loop 

### ISSUE THREAD

**Issue by qinfchen** [tgdwyer/WebCola#73]
I noticed that computeDerivatives in descent.ts would stuck in an infinite loop if the parameter x contains huge numbers:
```javacript
while (true) {
    var sd2 = 0;
    for (i = 0; i < this.k; ++i) {
        var dx = d[i] = x[i][u] - x[i][v];
        sd2 += d2[i] = dx * dx;
    }
    if (sd2 > 1e-9)
        break;
    var rd = this.offsetDir();
    for (i = 0; i < this.k; ++i)
        x[i][v] += rd[i];
    }
}
```

`dx` would be zero even though `x[i][u]` and `x[i][v]` aren't exactly same. This is because numbers in javascript are floating point and javascript rounds them to nearest number they can represent as 64 bit float.

**Comment by tgdwyer** [comment]
Interesting, thanks for letting us know.  Just how big are these numbers?  I guess the assumption is that spatial units are somewhere around pixels so we would expect them to be <10,000ish, not billions anyway.

**Comment by qinfchen** [comment]
Yes, we are using simga.js with webcola, when a node get dragged, the graph engine will rescale the other node positions. So the distance between the dragging node and other nodes increases exponentially. As a result, the node position can become extremely big (i think it was around 10^15)

**Comment by tgdwyer** [comment]
I think robustifying all of webcola to crazy big numbers will have to remain a "nice-to-have", however infinite loops are bad. So I've checked in the following:
```
var maxDisplaces = n; // avoid infinite loop in the case of numerical issues, such as huge values
while (maxDisplaces--) {
```

I suspect having such huge positions will probably cause issues elsewhere though... let me know.
