### ISSUE TITLE
Empty groups and minimum group dimensions

### ISSUE THREAD

**Issue by annorman** [tgdwyer/WebCola#74]
I'm trying to lay out some network architecture using cola and I'm finding that empty groups (subnets) are causing problems with findXNeighbours:

    TypeError: Cannot read property 'next' of null

From line 325 in rectangle.ts:

    var it = scanline.findIter(v);
    var u;
    while ((u = it[forward]()) !== null) {

So scanline is returning null for this iteration. It seems to work if I turn off avoidOverlaps though. I've tried to skip the while loop if 'it === null' but that causes an infinite loop.

My data structure is roughly:

    graph.groups = [
        { name: "vpc", width: 200, height: 200, groups: [1,2] },
        { name: "subnet", width: 50, height: 50 },
        { name: "subnet", width: 50, height: 50 }
    ]

Is this possible? Do groups require leaves? If I add a node to each of them it works. 

And a follow up to that: is it possible to specify minimum dimensions for groups?

**Comment by tgdwyer** [comment]
Groups really do need to have a child, either a leaf or another group.  I suppose we should either enforce this and give a nice friendly error message.

Minimum dimensions would definitely be a nice feature and not too hard to implement.  I'll add it to the todo list.  Wait, we need to create a todo list.  Let's put making a todo list on the todo list... doh! :-)

**Comment by tgdwyer** [comment]
OK, I created a [todo list](https://github.com/tgdwyer/WebCola/wiki) on the wiki:

**Comment by annorman** [comment]
Brilliant, many thanks!

**Comment by annorman** [comment]
Just as an aside to this - I've managed to get around the problem by adding a node with an 'invisible' property to the empty groups. My tick() method then ignores these nodes. The beneficial side effect of this is that the group then has a minimum size based on what I've set on the node.

Not sure if that solves the problem or just works around it, but if anyone runs across this - hope it helps :)
