### ISSUE TITLE
helper functions for adaptor

### ISSUE THREAD

**Issue by qinfchen** [tgdwyer/WebCola#87]
I noticed that this refactor https://github.com/tgdwyer/WebCola/commit/7c47ad8e6e6a3f1ef87df13378b3b3caba3839e8
removed drag-related help functions for adaptor. Is it intended?

```
-        adaptor.dragstart = colaDragstart;		
-        adaptor.dragend = colaDragend;		
-        adaptor.mouseover = colaMouseover;		
-        adaptor.mouseout = colaMouseout;
```
Comment on drag APIs (`colaDragstart`):
-If camel case is used, should it be renamed to `colaDragStart` for consistency ?
-`cola` prefix seems redundant since the name `cola` is already being used when invoking the function, `cola.colaDragstart`.

**Comment by tgdwyer** [comment]
Code reviews!  Awesome :-).

I've pushed some more clean-up.  ```adaptor``` is now renamed to ```Layout```, and these drag functions are now public methods on the Layout class.  They are all wrapped by the ```d3adaptor``` function anyway, so not really public facing, but they are all nicely camel-cased now for good measure.

FYI: there are a couple of reasons for this refactor:
 1) to minimize the dependency of cola on d3 and thus make it easier to use with other graphics libraries... To Do item now is to make such an adaptor.
 2) to be more consistent about using typescript for typesafety and more understandable code.
 3) to clean-up a bunch of crud (aka, technical debt) that was building up in the adaptor.

Thanks again for looking over this.  It really prompts me to keep simplifying the API.
