### ISSUE TITLE
Power Graph grid layout technique

### ISSUE THREAD

**Issue by automagic** [tgdwyer/WebCola#97]
I am interested in how you compute the optimal layout for the grid in the Tetris example at
http://marvl.infotech.monash.edu/webcola/examples/powergraphgridlayout.html   You are doing it server side, can you point me to any tips on how this is achieved?

**Comment by tgdwyer** [comment]
You mean this one:
http://marvl.infotech.monash.edu/webcola/examples/tetrisbugpowergraph.html

right now we model the layout aesthetics as a mathematical program
minimized on our server with a SAT solver.  We are writing up a paper about
the method right now.  I'll post the details here once the paper is
accepted.  For now, I'll send you a draft by private mail.

On 20 March 2015 at 02:33, James Connell <notifications@github.com> wrote:

> I am interested in how you compute the optimal layout for the grid in the
> Tetris example at
> http://marvl.infotech.monash.edu/webcola/examples/powergraphgridlayout.html
> You are doing it server side, can you point me to any tips on how this is
> achieved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgdwyer/WebCola/issues/97>.
>



-- 
Dr Tim Dwyer BSc BCS(Hons) PhD
Senior Lecturer and Larkins Fellow
Caulfield School of Information Technology
Mobile: 0481 240 767
(from overseas: +61 481 240 767)

**Comment by automagic** [comment]
Sounds very interesting, thank you.
