### ISSUE TITLE
Nodes and groups are drawn beyond the SVG boundaries

### ISSUE THREAD

**Issue by Gymnasiast** [tgdwyer/WebCola#98]
See the screenshot below. Some nodes are drawn beyond the SVG boundaries, and the group edges of the outer groups aren't even visible.

![schermafdruk van 2015-03-23 10 21 50](https://cloud.githubusercontent.com/assets/1478678/6781541/b1053caa-d16e-11e4-8a7c-221ed3a6154e.png)

This is the JSON data used for the visualisation: http://pastie.org/10047299
This is the (relevant part of the) code: http://pastie.org/10047304
If you need any more data, please say so.

**Comment by tgdwyer** [comment]
Are you sure that the bounds passed to webcola via the node width and height accurately reflect what is on screen?  I'm pretty swamped at the moment so I don't have time to debug your code, but I suggest you try to confirm that you are waiting for the appropriate events from the browser to set the node dimensions that are passed to webcola *after* they are fully realised by the renderer.

**Comment by tgdwyer** [comment]
I'm pretty sure this issue is in the app code so I'm going to close it for now.
